name: Build and Publish

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          architecture: x64

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Run the Gradle build
        run: ./gradlew clean build

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - run: echo "TAG_NOW=$(date +'%Y-%m-%d-%H-%M-%S')" >> $GITHUB_ENV

      - run: echo "ARTIFACT_NAME=$(cat settings.gradle.kts | grep rootProject | sed -nr 's/.*\"(.*)\"/\1/p')" >> $GITHUB_ENV

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.ARTIFACT_NAME }}:latest, ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.ARTIFACT_NAME }}:${{ env.TAG_NOW }}
          push: true
          platforms: linux/amd64

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}

      - run: echo ${{ env.TAG_NOW }}
      - run: echo ${{ env.ARTIFACT_NAME }}